/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAgentsGameManagerNameRouteImport } from './routes/api/agents/game-manager/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsGameManagerNameRoute =
  ApiAgentsGameManagerNameRouteImport.update({
    id: '/api/agents/game-manager/$name',
    path: '/api/agents/game-manager/$name',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agents/game-manager/$name': typeof ApiAgentsGameManagerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agents/game-manager/$name': typeof ApiAgentsGameManagerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agents/game-manager/$name': typeof ApiAgentsGameManagerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/agents/game-manager/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/agents/game-manager/$name'
  id: '__root__' | '/' | '/api/agents/game-manager/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentsGameManagerNameRoute: typeof ApiAgentsGameManagerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/game-manager/$name': {
      id: '/api/agents/game-manager/$name'
      path: '/api/agents/game-manager/$name'
      fullPath: '/api/agents/game-manager/$name'
      preLoaderRoute: typeof ApiAgentsGameManagerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentsGameManagerNameRoute: ApiAgentsGameManagerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
